// Where the universe sits on Earth: regions on six continents, topics in nearby cities joined to their region by
// real roads (OpenStreetMap/OSRM, simplified), and undersea-cable links between continents.
// Generated by scripts/universe/build-world.py — edit PLACES there and re-run, don't hand-edit world.json.
import data from "./world.json";
import type { NodeId } from "../types";

export interface Place {
  lon: number;
  lat: number;
  city: string;
}

export interface Road {
  /** Any two places in the same region (hub↔topic or topic↔topic): every place interconnects. */
  from: NodeId;
  to: NodeId;
  /** [lon, lat] polyline along real roads. */
  coords: [number, number][];
}

/** Full mesh between the six regions. */
export interface Cable {
  from: NodeId;
  to: NodeId;
}

export const WORLD_SOURCE: string = data.source;
export const PLACES: Record<NodeId, Place> = data.places as Record<NodeId, Place>;
export const ROADS: Road[] = data.roads as Road[];
export const CABLES: Cable[] = data.cables as Cable[];

/** The place a node is drawn at: its own, or (for leaves) the nearest ancestor that has one. */
export function placeOf(id: NodeId, parentOf: (id: NodeId) => NodeId | undefined): Place | null {
  let cur: NodeId | undefined = id;
  while (cur) {
    if (PLACES[cur]) return PLACES[cur];
    cur = parentOf(cur);
  }
  return null;
}
