apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudana-config
  namespace: cloudana
data:
  ORCHESTRATOR_CHAIN_RPC_URL: "https://base-sepolia.drpc.org"
  ORCHESTRATOR_RPC_TRANSPORT: "websocket"
  ORCHESTRATOR_EVENT_DRIVEN_ENABLED: "true"
  ORCHESTRATOR_EVENT_DEBOUNCE_MS: "2000"
  POUW_MIN_DIFFICULTY: "8"
  POUW_VERIFIER_CONTRACT_ADDRESS: "0xc15c61E35D6d73dEf14460a1C7010fd169eD2e7F"
  POUW_MINING_POOL_WORKLOAD_ID: "999"
  MINING_REWARDS_ENABLED: "true"
  REWARD_CONTRACT_ADDRESS: "0x427830A20C4752eb30C47e0d2572A457ebF4A8AD"
  CHAIN_ID: "84532"
