/**
 * Curated workstation templates (docs/WORKSTATIONS.md §6), category "Workstations".
 * The console copies gpu/access/workdir/sshPort/tokenEnv/tokenQuery into the WorkstationSpec; createDeployment
 * also fills any of workdir/sshPort/tokenEnv/tokenQuery the spec leaves out from the template.
 *
 * Image references marked UNVERIFIED were not pulled from this machine (no Docker here, docs §9):
 * the tag, port or env convention is from the image's published docs and must be checked on a GPU node.
 */
import type { Template } from "../types/template.js";

export const WORKSTATIONS_TITLE = "Workstations";

interface W {
  id: string;
  name: string;
  summary: string;
  image: string;
  ports: number[];
  cpu: number;
  memMb: number;
  storageMb: number;
  gpu: NonNullable<Template["gpu"]>;
  access: NonNullable<Template["access"]>;
  workdir: string;
  sshPort?: number;
  tokenEnv?: string;
  tokenQuery?: string;
  logo: string | null;
  notes: string;
}

const ITEMS: W[] = [
  {
    // UNVERIFIED tag: Jupyter Docker Stacks publish CUDA variants as cuda12-* on quay.io.
    id: "ws-jupyter-cuda", name: "JupyterLab (PyTorch, CUDA)", summary: "JupyterLab with PyTorch on an assigned GPU. The default GPU workstation.",
    image: "quay.io/jupyter/pytorch-notebook:cuda12-latest", ports: [8888], cpu: 4000, memMb: 16384, storageMb: 20480,
    gpu: { count: 1, class: "any" }, access: { web: { port: 8888, path: "/lab" }, ssh: false },
    workdir: "/home/jovyan/work", tokenEnv: "JUPYTER_TOKEN", tokenQuery: "token", logo: "jupyter",
    notes: "Opens with a one-time token in the link.",
  },
  {
    id: "ws-code-server", name: "VS Code (code-server)", summary: "VS Code in the browser, with a persistent project folder.",
    image: "codercom/code-server:latest", ports: [8080], cpu: 2000, memMb: 4096, storageMb: 10240,
    gpu: { count: 0 }, access: { web: { port: 8080 }, ssh: false },
    workdir: "/home/coder/project", tokenEnv: "PASSWORD", logo: "coder",
    notes: "The password is generated by the node and shown in the console (it cannot go in the link).",
  },
  {
    // UNVERIFIED: linuxserver KasmVNC images take PASSWORD (user "abc") for basic auth.
    id: "ws-linux-desktop", name: "Linux desktop (KDE)", summary: "A full Ubuntu KDE desktop in your browser.",
    image: "lscr.io/linuxserver/webtop:ubuntu-kde", ports: [3000], cpu: 2000, memMb: 4096, storageMb: 20480,
    gpu: { count: 0 }, access: { web: { port: 3000 }, ssh: false },
    workdir: "/config", tokenEnv: "PASSWORD", logo: "kde",
    notes: "Sign in as user abc with the password shown in the console.",
  },
  {
    // UNVERIFIED tag: RunPod's PyTorch images run sshd and read the key from PUBLIC_KEY.
    id: "ws-pytorch-ssh", name: "PyTorch over SSH", summary: "PyTorch + CUDA with sshd: bring your own key and work from your terminal or IDE.",
    image: "runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04", ports: [22], cpu: 4000, memMb: 16384, storageMb: 30720,
    gpu: { count: 1, class: "any" }, access: { ssh: true },
    workdir: "/workspace", sshPort: 22, logo: "pytorch",
    notes: "SSH only: paste your public key. Login user root.",
  },
  {
    // UNVERIFIED tag: yanwk/comfyui-boot publishes CUDA-specific tags; latest assumed.
    id: "ws-comfyui", name: "ComfyUI", summary: "Node-based Stable Diffusion / Flux image workflows.",
    image: "yanwk/comfyui-boot:latest", ports: [8188], cpu: 4000, memMb: 16384, storageMb: 40960,
    gpu: { count: 1, minVramGb: 8, class: "any" }, access: { web: { port: 8188 }, ssh: false },
    workdir: "/root", logo: null,
    notes: "No login: anyone with the link can use it while it runs.",
  },
  {
    // UNVERIFIED port: the image's README maps 8080 (the contract's 7860 is the stock A1111 port).
    id: "ws-sd-webui", name: "Stable Diffusion WebUI", summary: "AUTOMATIC1111 web UI for image generation.",
    image: "universonic/stable-diffusion-webui:latest", ports: [8080], cpu: 4000, memMb: 16384, storageMb: 40960,
    gpu: { count: 1, minVramGb: 8, class: "any" }, access: { web: { port: 8080 }, ssh: false },
    workdir: "/app/stable-diffusion-webui/models", logo: null,
    notes: "No login: anyone with the link can use it while it runs.",
  },
  {
    // Single-container variant: Open WebUI's :ollama tag bundles Ollama (the two-container setup is not supported).
    id: "ws-ollama-webui", name: "Ollama + Open WebUI", summary: "Chat with open LLMs on your own GPU — Ollama and Open WebUI in one container.",
    image: "ghcr.io/open-webui/open-webui:ollama", ports: [8080], cpu: 4000, memMb: 16384, storageMb: 40960,
    gpu: { count: 1, minVramGb: 8, class: "any" }, access: { web: { port: 8080 }, ssh: false },
    workdir: "/app/backend/data", logo: "ollama",
    notes: "Create the admin account on first open. Models are kept on the volume.",
  },
  {
    id: "ws-blender", name: "Blender", summary: "Blender in a browser desktop, rendering on an assigned GPU.",
    image: "lscr.io/linuxserver/blender:latest", ports: [3000], cpu: 4000, memMb: 8192, storageMb: 20480,
    gpu: { count: 1, class: "any" }, access: { web: { port: 3000 }, ssh: false },
    workdir: "/config", tokenEnv: "PASSWORD", logo: "blender",
    notes: "Sign in as user abc with the password shown in the console.",
  },
];

export const WORKSTATION_TEMPLATES: Template[] = ITEMS.map((w) => ({
  id: w.id,
  name: w.name,
  path: w.id,
  readme:
    `# ${w.name}\n\n${w.summary}\n\nImage: \`${w.image}\` · ${w.gpu.count ? `${w.gpu.count} GPU` : "CPU only"} · ` +
    `files in \`${w.workdir}\` are kept on a volume.\n\n${w.notes}`,
  summary: w.summary,
  logoUrl: w.logo ? `https://cdn.simpleicons.org/${w.logo}` : null,
  deploy: "",
  githubUrl: "",
  persistentStorageEnabled: true,
  config: { ssh: w.access.ssh },
  kind: "workstation",
  category: WORKSTATIONS_TITLE,
  curated: true,
  image: w.image,
  command: [],
  ports: w.ports,
  cpu: w.cpu,
  memMb: w.memMb,
  storageMb: w.storageMb,
  secretEnv: [],
  env: {},
  files: [],
  gpu: w.gpu,
  access: w.access,
  workdir: w.workdir,
  ...(w.sshPort !== undefined && { sshPort: w.sshPort }),
  ...(w.tokenEnv && { tokenEnv: w.tokenEnv }),
  ...(w.tokenQuery && { tokenQuery: w.tokenQuery }),
}));
